# Generated by Django 2.1.5 on 2019-02-09 10:20

from django.db import migrations, models
import django.db.models.deletion
from users.models import CustomUser, ContentProvider

def fix_custom_user_owner(apps, schema_editor):
    users_query = CustomUser.objects.all()
    cont_prov = ContentProvider.objects.get(customuser__username__istartswith="adm")
    for user in users_query:
        # user.content_provider =
        continue

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ContentProviderDefault', max_length=127)),
                ('description', models.TextField()),
                ('logo', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='content_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.ContentProvider'),
        ),
    ]
